server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: funcionalidad/comunicacion-productos-usuarios
          uri: https://github.com/mg0mez/trading-plataform
          search-paths: config-data
  application:
    name: config-service
          